name: Scheduled Pipeline - full execution
on:
  schedule:
    - cron: "10 12 * * *"
  workflow_dispatch:

jobs:
  trigger-tessa:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger TESSA
        run: curl -X POST http://164.68.113.171:3000/api/projects/MS9/pipelines/ba1c8028-634f-4b8a-bf67-5aaaf009f71d/trigger
